/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.Handler;

import Model.Game;
import Model.InvalidGame;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author DELL
 */
public class CurrentGame extends javax.swing.JFrame {

    /**
     * Creates new form CurrentGame
     */

    private Game game;
    private Handler handler;

   
    
    public CurrentGame(Game game, Continue parentFrame) {
        
        initComponents();
        this.game=game;
        loadtable();
    }

    private CurrentGame() {
       //mo2ktan 3shan el error bs
    }
class sudokuTable extends javax.swing.table.DefaultTableModel{
    private final List<int []>edit;

        public sudokuTable(List<int[]> edit, Object[][] data, Object[] columnNames) {
            super(data, columnNames);
            this.edit = edit;
        }

       

        @Override
        public boolean isCellEditable(int row, int column) {
            for(int[] p : edit){
            if(p[0] == row && p[1]==column){
            return true;
            }
            }
            return false; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return Integer.class; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        }
        

    
    
    
}

private void loadtable(){
Object[][] data = new Object[9][9];
int[][] board = game.getBoard();
for (int i = 0 ; i < 9 ; i ++ ) {
for (int j = 0 ; j < 9 ; j ++ ) {
if (board[i][j] == 0){
data[i][j]=null;
}else{
data[i][j]  = board[i][j];
}
}
}
String[] cols = {"", "", "", "", "", "", "", "", ""};
matrixGame.setModel(
new sudokuTable(game.getEditable(),data, cols)
    );

matrixGame.getModel().addTableModelListener(l -> {
int r = l.getFirstRow();
int c = l.getColumn();
Object val = matrixGame.getValueAt(r, c);
try{
if(val == null){
 game.editcell(r, c, 0);

}
else{

game.editcell(r, c, (int)val);
}}
catch(IllegalArgumentException e){
    JOptionPane.showMessageDialog(this, "INVALID VALUE ENTERED/ENTERED DATA IN UNEDITABLE BLOCK", "ERROR",ERROR);
}
});
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        matrixGame = new javax.swing.JTable();
        solveBUTTON = new javax.swing.JButton();
        undoBUTTON = new javax.swing.JButton();
        validateBUTTON = new javax.swing.JButton();
        titleTXT = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        matrixGame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        matrixGame.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(matrixGame);
        if (matrixGame.getColumnModel().getColumnCount() > 0) {
            matrixGame.getColumnModel().getColumn(0).setHeaderValue("");
            matrixGame.getColumnModel().getColumn(1).setHeaderValue("");
            matrixGame.getColumnModel().getColumn(2).setHeaderValue("");
            matrixGame.getColumnModel().getColumn(3).setHeaderValue("");
            matrixGame.getColumnModel().getColumn(4).setHeaderValue("");
            matrixGame.getColumnModel().getColumn(5).setHeaderValue("");
            matrixGame.getColumnModel().getColumn(6).setHeaderValue("");
            matrixGame.getColumnModel().getColumn(7).setHeaderValue("");
            matrixGame.getColumnModel().getColumn(8).setPreferredWidth(20);
            matrixGame.getColumnModel().getColumn(8).setHeaderValue("");
        }

        solveBUTTON.setText("Solve");
        solveBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveBUTTONActionPerformed(evt);
            }
        });

        undoBUTTON.setText("Undo");
        undoBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBUTTONActionPerformed(evt);
            }
        });

        validateBUTTON.setText("Validate");
        validateBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateBUTTONActionPerformed(evt);
            }
        });

        titleTXT.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 36)); // NOI18N
        titleTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTXT.setText("Sudoku Game!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titleTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(validateBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(undoBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(solveBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(solveBUTTON)
                            .addComponent(undoBUTTON)
                            .addComponent(validateBUTTON))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        pack();
    }//GEN-END:initComponents

    private void validateBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateBUTTONActionPerformed
       /* int[][] board = game.getBoard();
        boolean[][] result = control.verifyGame(board);
        
        for(int i = 0 ; i < 9 ; i++)
        {
            for(int j = 0 ; j < 9 ; j ++)
            {
                if(!result[i][j])
                {
                    //kda y3ne fe cell mesh sah!!
                    //neshuf ba han-handle ezay
                    JOptionPane.showMessageDialog(this,"ERROR! AN INVALID CELL FOUND!");
                }
            }
        }*/

    }//GEN-LAST:event_validateBUTTONActionPerformed

    private int numberOfEmptySpaces()
    {
        int[][] board=game.getBoard();
        int count=0;
        for(int r=0;r<board.length;r++)
        {
          for(int c=0;c<board[r].length;c++)
          {
              if(board[r][c]==0)
              {
                  count++;
              }
          }
        }
         return count;
    
    }
    private void solveBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveBUTTONActionPerformed
       
      int[]solve =null;
      try {
       solve = handler.solveGame(this.game); 
      }
      catch (InvalidGame e){
       JOptionPane.showMessageDialog(this, "ERROR!");
      }
        if(solve!=null){
        try{  //3shan DE bt-throw exception
           
           //722na fekrt enena bnady el implementation
          
            
        
            if(solve.length!=15)
            {
            throw new InvalidGame("solution is not in the correct format");//in case haga was wrong 
            }
            for(int i= 0;i<solve.length;i+=3)
            {
            int row = solve[i];
            int col = solve[i + 1];
            int value = solve[i + 2];
            matrixGame.setValueAt(value, row, col);
            game.getBoard()[row][col] = value;//b update the actual board mesh just for display
            }
            JOptionPane.showMessageDialog(this, "GAME SOLVED!!!");
        }
        catch(InvalidGame exception)
        {
            JOptionPane.showMessageDialog(this, "ERROR!");
        }
        }
        
    }//GEN-LAST:event_solveBUTTONActionPerformed

    private void undoBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undoBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable matrixGame;
    private javax.swing.JButton solveBUTTON;
    private javax.swing.JLabel titleTXT;
    private javax.swing.JButton undoBUTTON;
    private javax.swing.JButton validateBUTTON;
    // End of variables declaration//GEN-END:variables

    
}
